# Generated by Django 6.1.1 on 2026-10-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('HVAC', 'HVAC'), ('Kitchen', 'Kitchen'), ('Laundry', 'Laundry'), ('Lighting', 'Lighting'), ('Electronics', 'Electronics'), ('Water Heating', 'Water Heating'), ('Other', 'Other')], default='Other', max_length=30)),
                ('power_watts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_hours_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_per_period', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('standby_power_watts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='homes.home')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
