# Generated by Django 6.1.1 on 2026-10-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(blank=True, max_length=120)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='TariffTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('maximum_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('rate_per_kwh', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_tiers', to='billing.tariff')),
            ],
            options={
                'ordering': ['minimum_kwh'],
            },
        ),
    ]
