# Generated by Django 6.1.1 on 2026-10-02 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_value_kwh', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('reading_date', models.DateField()),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('csv_import', 'CSV Import'), ('smart_meter', 'Smart Meter'), ('authorized_utility_api', 'Authorized Utility API')], default='manual', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='homes.home')),
            ],
            options={
                'ordering': ['reading_date'],
            },
        ),
    ]
